eno=int(input("ENTER EMPLOYEE NO:"))
ename=input("ENTER EMPLOYEE NAME:")
esal=float(input("ENTER EMPLOYEE SALARY:"))
eaddr=input("ENTER EMPLOYEE ADDRESS:")
married=bool(input("EMPLOYEE MARRIAGE STATUS[True|False]:"))
print("Please Confirm Your Information..")
print("EMPLOYEE NUMBER:",eno)
print("EMPLOYEE NAME:",ename)
print("EMPLOYEE ADDRESS:",eaddr)
print("EMPLOYEE SALARY:",esal)
print("EMPLOYEE MARRIAGE STATUS:",married)
